supervisor:
  llmProvider: OPENAI
  model: gpt-4o-mini
  temperature: 0

workers:
  - name: webSearchAgent
    llmProvider: OPENAI
    model: gpt-4o
    temperature: 0.5
    systemMessage: You are a kind chat assistant with access to tavily for web search
    tools: [tavily]
  - name: mathAgent
    llmProvider: OPENAI
    model: gpt-4o
    temperature: 0
    systemMessage: You are an math expert with access to a calculator tool
    tools: [calculator]
  - name: wikiAgent
    llmProvider: OPENAI
    model: gpt-4o
    temperature: 0
    systemMessage: You are a kind chat assistant with access to wikipedia search
    tools: [wikipedia]
  - name: codeAgent
    llmProvider: OPENAI
    model: gpt-4o
    temperature: 0
    systemMessage: You are a kind code expert to answer any coding related questions
    tools: []
